# Generated by Django 5.2 on 2025-05-05 11:20

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RoleType',
            fields=[
                ('RoleID', models.AutoField(primary_key=True, serialize=False)),
                ('RoleName', models.CharField(max_length=100)),
                ('Status', models.IntegerField(default=1)),
                ('CreatedAt', models.DateTimeField(auto_now_add=True)),
                ('UpdatedAt', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'RoleType',
            },
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('StatusID', models.AutoField(primary_key=True, serialize=False)),
                ('StatusName', models.CharField(max_length=255)),
                ('CreatedAt', models.DateTimeField(auto_now_add=True)),
                ('UpdatedAt', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'Status',
            },
        ),
        migrations.CreateModel(
            name='UserDetails',
            fields=[
                ('UserID', models.AutoField(primary_key=True, serialize=False)),
                ('FirstName', models.CharField(max_length=255)),
                ('LastName', models.CharField(max_length=255)),
                ('Email', models.CharField(max_length=100, unique=True, validators=[django.core.validators.EmailValidator()])),
                ('Password', models.CharField(max_length=255)),
                ('DateofBirth', models.CharField(max_length=20)),
                ('CreatedAt', models.DateTimeField(auto_now_add=True)),
                ('UpdatedAt', models.DateTimeField(auto_now=True)),
                ('RoleType', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.roletype')),
                ('Status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.status')),
            ],
            options={
                'db_table': 'UserDetails',
            },
        ),
    ]
